# Installing TensorFlow

In [ ]:
!pip install grpcio==1.24.3
!pip install tensorflow==2.2.0

#Importing TensorFlow

In [1]:
import tensorflow as tf

In [ ]:
if not tf.__version__ == '2.2.0':
    print(tf.__version__)
    raise ValueError('please upgrade to TensorFlow 2.2.0, or restart your Kernel (Kernel->Restart & Clear Output)')

# tf.function and AutoGraph

In [2]:
a = tf.constant([2], name = 'constant_a')

In [3]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [4]:
b = tf.constant([3], name = 'constant_b')

In [5]:
b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [6]:
tf.print(a.numpy()[0])

2


In [7]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms
    print(c)
    return c

In [8]:
result = add(a,b)

Tensor("Add:0", shape=(1,), dtype=int32)


In [9]:
result

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [10]:
tf.print(result[0])

5


In [11]:
A = add(8,9)

Tensor("Add:0", shape=(), dtype=int32)


In [12]:
A

<tf.Tensor: shape=(), dtype=int32, numpy=17>

# Defining multidimensional arrays using TensorFlow

In [14]:
Scalar = tf.constant(2)
Scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
Vector = tf.constant([5,6,2])
Vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 2], dtype=int32)>

In [16]:
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [17]:
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
Tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11]]], dtype=int32)>

In [18]:
print ("Scalar (1 entry):\n %s \n" % Scalar)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 



In [19]:
print ("Vector (3 entries) :\n %s \n" % Vector)

Vector (3 entries) :
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 



In [20]:
print ("Matrix (3x3 entries):\n %s \n" % Matrix)

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 



In [21]:
print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [22]:
Scalar.shape

TensorShape([])

In [23]:
Vector.shape

TensorShape([3])

In [24]:
Matrix.shape

TensorShape([3, 3])

In [25]:
Tensor.shape

TensorShape([3, 3, 3])

In [26]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_one

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [27]:
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
Matrix_two

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)>

In [28]:
@tf.function
def add():
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    return add_1_operation

In [31]:
print("Defined using tensorflow function :")
add_1_operation = add()
print(add_1_operation)

Defined using tensorflow function :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [32]:
print("Defined using normal expressions :")
add_2_operation = Matrix_one + Matrix_two
print(add_2_operation)

Defined using normal expressions :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [33]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

In [34]:
Matrix_two = tf.constant([[2,3],[3,4]])
Matrix_two

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

In [35]:
@tf.function
def mathmul():
  return tf.matmul(Matrix_one, Matrix_two)

In [36]:
mul_operation = mathmul()

print ("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


# Variables

In [37]:
v = tf.Variable(0)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

In [38]:
@tf.function
def increment_by_one(v):
        v = tf.add(v,1)
        return v

In [39]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


# Operations

In [40]:
a = tf.constant([5])
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [41]:
b = tf.constant([2])
b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [42]:
c = tf.add(a,b)
c

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>

In [43]:
d = tf.subtract(a,b)
d

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [44]:
print ('c =: %s' % c)

c =: tf.Tensor([7], shape=(1,), dtype=int32)


In [45]:
print ('d =: %s' % d)

d =: tf.Tensor([3], shape=(1,), dtype=int32)
